name: Rchain
description: A Blockchain with dart.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.12.0 <3.0.0"

# dependencies:
#   path: ^1.8.0
dev_dependencies:
  pedantic: ^1.10.0
dependencies:
  crypto: ^3.0.1
  meta: ^1.4.0
  shelf: ^1.2.0
  shelf_router: ^1.1.0
